trigger:
- master

variables: { 
  mlWorkspaceConnection: 'aml-workshop',
  mlWorkspaceName: 'aml-workshop',
  resourceGroupName: 'aml-workshop'
}

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@1
  displayName: 'Install the CLI'
  inputs:
    azureSubscription: $(mlWorkspaceConnection)
    scriptLocation: inlineScript
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@1
  displayName: 'Attach folder to workspace'
  inputs:
    azureSubscription: $(mlWorkspaceConnection)
    scriptLocation: inlineScript
    inlineScript: 'az ml folder attach -w $(mlWorkspaceName) -g $(resourceGroupName)'
    workingDirectory: '3-mlops'


- task: AzureCLI@1
  displayName: 'Create ML pipeline'
  inputs:
    azureSubscription: $(mlWorkspaceConnection)
    scriptLocation: inlineScript
    inlineScript: 'az ml pipeline create --name trainattrition -y training-ml-pipeline.yml'
    workingDirectory: '3-mlops'

- task: AzureCLI@1
  displayName: 'Submit script run'
  inputs:
    azureSubscription: $(mlWorkspaceConnection)
    scriptLocation: inlineScript
    inlineScript: 'az ml run submit-script -c train -e test train_explain.py'
    workingDirectory: '3-mlops'
